import type { Metadata } from "next";
import { Cormorant_Garamond, Montserrat } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import { CheckoutProvider } from "@/context/CheckoutContext";
import CartDrawer from "@/components/layout/CartDrawer";
import CheckoutModal from "@/components/checkout/CheckoutModal";
import UpsellPopup from "@/components/checkout/UpsellPopup";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-cormorant",
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-montserrat",
  display: "swap",
});

const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") || "https://rebelle.ma";

export const metadata: Metadata = {
  // metadataBase makes relative OG / Twitter URLs resolve against the
  // canonical production origin (rebelle.ma), needed for social shares.
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Rebelle — Sacs Luxury Premium au Maroc",
    template: "%s | Rebelle",
  },
  description:
    "Rebelle est la référence des sacs de luxe pour femmes au Maroc. Qualité premium, paiement à la livraison, livraison rapide partout au Maroc.",
  keywords: [
    "sacs femme maroc",
    "sacs luxury maroc",
    "sacs premium casablanca",
    "sacs de luxe maroc",
    "maroquinerie maroc",
    "rebelle sacs",
    "sacs à main maroc",
    "paiement livraison maroc",
  ],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "fr_MA",
    url: SITE_URL,
    siteName: "Rebelle",
    title: "Rebelle — Sacs Luxury Premium au Maroc",
    description:
      "La référence des sacs luxury pour femmes modernes au Maroc. Qualité d'exception, paiement à la livraison.",
    images: [
      {
        url: "/assets/images/hero/hero-bg1.jpg",
        width: 1672,
        height: 941,
        alt: "Rebelle — Sacs Luxury Premium au Maroc",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Rebelle — Sacs Luxury Premium au Maroc",
    description: "La référence des sacs luxury pour femmes modernes au Maroc.",
    images: ["/assets/images/hero/hero-bg1.jpg"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  // Favicons are auto-generated by Next.js from app/icon.jpg and app/apple-icon.jpg
};

// Structured data — helps Google build a Knowledge Panel & Sitelinks
// search box. Lives in <head> as JSON-LD.
const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Rebelle",
  alternateName: "Maison Rebelle",
  url: SITE_URL,
  logo: `${SITE_URL}/assets/images/Logo/logo.png`,
  description:
    "Maison Rebelle — sacs de luxe pour femmes au Maroc. Paiement à la livraison.",
  address: {
    "@type": "PostalAddress",
    addressCountry: "MA",
  },
  contactPoint: {
    "@type": "ContactPoint",
    telephone: "+212622049015",
    contactType: "customer service",
    areaServed: "MA",
    availableLanguage: ["French", "Arabic"],
  },
  sameAs: ["https://www.instagram.com/rebelle.v3"],
};

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "Rebelle",
  url: SITE_URL,
  inLanguage: "fr-MA",
  publisher: { "@type": "Organization", name: "Rebelle" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="fr"
      className={`${cormorant.variable} ${montserrat.variable}`}
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <meta name="theme-color" content="#810B38" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
      </head>
      <body className="font-montserrat antialiased bg-white">
        <CartProvider>
          <CheckoutProvider>
            {children}
            <CartDrawer />
            <CheckoutModal />
            <UpsellPopup />
          </CheckoutProvider>
        </CartProvider>
      </body>
    </html>
  );
}
